use crate::core::http_client::create_proxy_client;
use crate::AppState;
use chrono::{DateTime, Utc};
use reqwest::Method;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::Arc;
use tauri::State;

use super::hme_storage::HmeStorage;

const BASE_URL_V1: &str = "https://p68-maildomainws.icloud.com/v1/hme";
const BASE_URL_V2: &str = "https://p68-maildomainws.icloud.com/v2/hme";
const COOKIE_VALIDATE_URL: &str = "https://setup.icloud.com/setup/ws/1/validate";
const CLIENT_BUILD_NUMBER: &str = "2536Project32";
const CLIENT_MASTERING_NUMBER: &str = "2536B20";
const DEFAULT_LABEL: &str = "ATM HME";
const DEFAULT_NOTE: &str = "Generated by ATM HME";
const MAX_GENERATE_COUNT: u32 = 5;
const MAX_CONSECUTIVE_FAILS: usize = 3;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HmeEmailItem {
    pub anonymous_id: String,
    pub label: String,
    pub hme: String,
    pub is_active: bool,
    pub create_timestamp: i64,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HmeGenerateResponse {
    pub requested: u32,
    pub generated: Vec<String>,
    pub failed: u32,
    pub stopped_early: bool,
    pub errors: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HmeBatchActionResponse {
    pub total: usize,
    pub success: usize,
    pub failed: usize,
    pub errors: Vec<String>,
}

struct HmeApiClient {
    cookie: String,
}

impl HmeApiClient {
    fn new(cookie: String) -> Self {
        Self { cookie }
    }

    fn with_headers(
        &self,
        request: reqwest::RequestBuilder,
        with_json_content_type: bool,
    ) -> reqwest::RequestBuilder {
        let mut req = request
            .header("Connection", "keep-alive")
            .header("Pragma", "no-cache")
            .header("Cache-Control", "no-cache")
            .header("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36")
            .header("Accept", "*/*")
            .header("Origin", "https://www.icloud.com")
            .header("Referer", "https://www.icloud.com/")
            .header("Accept-Language", "en-US,en;q=0.9")
            .header("Cookie", self.cookie.trim());

        if with_json_content_type {
            req = req.header("Content-Type", "application/json");
        }

        req
    }

    async fn request_hme(
        &self,
        method: Method,
        url: &str,
        body: Option<Value>,
    ) -> Result<Value, String> {
        let proxy_client =
            create_proxy_client().map_err(|e| format!("Failed to create HTTP client: {}", e))?;

        let mut request = proxy_client.request(method, url).query(&[
            ("clientBuildNumber", CLIENT_BUILD_NUMBER),
            ("clientMasteringNumber", CLIENT_MASTERING_NUMBER),
            ("clientId", ""),
            ("dsid", ""),
        ]);

        request = self.with_headers(request, body.is_some());
        if let Some(payload) = body {
            request = request.json(&payload);
        }

        self.send(request).await
    }

    async fn validate_cookie(&self) -> Result<Value, String> {
        let proxy_client =
            create_proxy_client().map_err(|e| format!("Failed to create HTTP client: {}", e))?;
        let request = proxy_client.request(Method::POST, COOKIE_VALIDATE_URL).query(&[
            ("clientBuildNumber", CLIENT_BUILD_NUMBER),
            ("clientMasteringNumber", CLIENT_MASTERING_NUMBER),
            ("clientId", ""),
            ("dsid", ""),
        ]);
        let request = self.with_headers(request, false);
        self.send(request).await
    }

    async fn send(&self, request: reqwest::RequestBuilder) -> Result<Value, String> {
        let response = request
            .send()
            .await
            .map_err(|e| format!("Request failed: {}", e))?;

        let status = response.status();
        let content_type = response
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("")
            .to_ascii_lowercase();
        let body = response
            .text()
            .await
            .map_err(|e| format!("Failed to read response: {}", e))?;

        if matches!(status.as_u16(), 401 | 403 | 421) {
            return Err(format!("Cookie expired or invalid (HTTP {})", status.as_u16()));
        }

        if !status.is_success() {
            return Err(format!("HTTP {}: {}", status.as_u16(), truncate_for_error(&body)));
        }

        if !content_type.contains("json") && !content_type.contains("text/plain") {
            let lowered = body.to_ascii_lowercase();
            if lowered.contains("<html") || lowered.contains("<title") {
                return Err("Cookie expired or invalid (unexpected HTML response)".to_string());
            }
        }

        serde_json::from_str::<Value>(&body)
            .map_err(|e| format!("Failed to parse response: {} ({})", e, truncate_for_error(&body)))
    }
}

fn truncate_for_error(text: &str) -> String {
    const MAX: usize = 240;
    let trimmed = text.trim();
    if trimmed.len() <= MAX {
        trimmed.to_string()
    } else {
        format!("{}...", &trimmed[..MAX])
    }
}

fn parse_api_error(value: &Value) -> String {
    if let Some(reason) = value.get("reason").and_then(|v| v.as_str()) {
        return reason.to_string();
    }

    if let Some(error) = value.get("error") {
        if let Some(message) = error.as_str() {
            return message.to_string();
        }
        if let Some(error_message) = error.get("errorMessage").and_then(|v| v.as_str()) {
            return error_message.to_string();
        }
        if let Some(message) = error.get("message").and_then(|v| v.as_str()) {
            return message.to_string();
        }
    }

    "Unknown iCloud API error".to_string()
}

fn ensure_success(value: &Value) -> Result<(), String> {
    if value
        .get("success")
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
    {
        Ok(())
    } else {
        Err(parse_api_error(value))
    }
}

fn format_timestamp(timestamp_ms: i64) -> String {
    let normalized = if timestamp_ms.abs() < 1_000_000_000_000 {
        timestamp_ms.saturating_mul(1000)
    } else {
        timestamp_ms
    };
    DateTime::<Utc>::from_timestamp_millis(normalized)
        .map(|dt| dt.to_rfc3339())
        .unwrap_or_default()
}

fn get_hme_storage(state: &State<'_, AppState>) -> Result<Arc<HmeStorage>, String> {
    state
        .hme_storage
        .lock()
        .map_err(|_| "Failed to access HME storage state".to_string())?
        .clone()
        .ok_or_else(|| "HME storage not initialized".to_string())
}

fn get_cookie_from_state(state: &State<'_, AppState>) -> Result<String, String> {
    let cookie = state
        .hme_cookie
        .lock()
        .map_err(|_| "Failed to access iCloud HME cookie state".to_string())?
        .clone();
    let normalized = cookie.unwrap_or_default().trim().to_string();

    if normalized.is_empty() {
        Err("Cookie is not set".to_string())
    } else {
        Ok(normalized)
    }
}

fn map_hme_item(item: &Value) -> Option<HmeEmailItem> {
    let anonymous_id = item.get("anonymousId")?.as_str()?.to_string();
    let label = item
        .get("label")
        .and_then(|v| v.as_str())
        .unwrap_or_default()
        .to_string();
    let hme = item
        .get("hme")
        .and_then(|v| v.as_str())
        .unwrap_or_default()
        .to_string();
    let is_active = item
        .get("isActive")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let create_timestamp = item
        .get("createTimestamp")
        .and_then(|v| v.as_i64())
        .unwrap_or_default();

    Some(HmeEmailItem {
        anonymous_id,
        label,
        hme,
        is_active,
        create_timestamp,
        created_at: format_timestamp(create_timestamp),
    })
}

#[tauri::command]
pub async fn hme_set_cookie(cookie: String, state: State<'_, AppState>) -> Result<(), String> {
    let normalized = cookie.trim();
    if normalized.is_empty() {
        return Err("Cookie cannot be empty".to_string());
    }

    let mut guard = state
        .hme_cookie
        .lock()
        .map_err(|_| "Failed to update iCloud HME cookie state".to_string())?;
    *guard = Some(normalized.to_string());
    Ok(())
}

#[tauri::command]
pub async fn hme_clear_cookie(state: State<'_, AppState>) -> Result<(), String> {
    let mut guard = state
        .hme_cookie
        .lock()
        .map_err(|_| "Failed to clear iCloud HME cookie state".to_string())?;
    *guard = None;
    Ok(())
}

#[tauri::command]
pub async fn hme_get_cookie(state: State<'_, AppState>) -> Result<Option<String>, String> {
    let cookie = state
        .hme_cookie
        .lock()
        .map_err(|_| "Failed to read iCloud HME cookie state".to_string())?
        .clone();
    Ok(cookie.filter(|v| !v.trim().is_empty()))
}

#[tauri::command]
pub async fn hme_has_cookie(state: State<'_, AppState>) -> Result<bool, String> {
    let has_cookie = state
        .hme_cookie
        .lock()
        .map_err(|_| "Failed to read iCloud HME cookie state".to_string())?
        .as_ref()
        .map(|v| !v.trim().is_empty())
        .unwrap_or(false);
    Ok(has_cookie)
}

#[tauri::command]
pub async fn hme_validate_cookie(state: State<'_, AppState>) -> Result<bool, String> {
    let cookie = get_cookie_from_state(&state)?;
    let client = HmeApiClient::new(cookie);
    let response = client.validate_cookie().await?;
    Ok(response.get("dsInfo").is_some() || response.get("webservices").is_some())
}

#[tauri::command]
pub async fn hme_generate(
    count: u32,
    label: Option<String>,
    state: State<'_, AppState>,
) -> Result<HmeGenerateResponse, String> {
    if count == 0 {
        return Err("Count must be greater than 0".to_string());
    }

    let requested = count.min(MAX_GENERATE_COUNT);
    let cookie = get_cookie_from_state(&state)?;
    let client = HmeApiClient::new(cookie);
    let final_label = label
        .unwrap_or_else(|| DEFAULT_LABEL.to_string())
        .trim()
        .to_string();
    let final_label = if final_label.is_empty() {
        DEFAULT_LABEL.to_string()
    } else {
        final_label
    };

    let mut generated = Vec::new();
    let mut errors = Vec::new();
    let mut consecutive_fails = 0usize;
    let mut stopped_early = false;

    for _ in 0..requested {
        let generate_resp = client
            .request_hme(
                Method::POST,
                &format!("{}/generate", BASE_URL_V1),
                Some(json!({ "langCode": "en-us" })),
            )
            .await;

        let generated_value = match generate_resp {
            Ok(value) => value,
            Err(err) => {
                consecutive_fails += 1;
                errors.push(format!("Generate failed: {}", err));
                if consecutive_fails >= MAX_CONSECUTIVE_FAILS {
                    stopped_early = true;
                    break;
                }
                continue;
            }
        };

        if let Err(err) = ensure_success(&generated_value) {
            consecutive_fails += 1;
            errors.push(format!("Generate failed: {}", err));
            if consecutive_fails >= MAX_CONSECUTIVE_FAILS {
                stopped_early = true;
                break;
            }
            continue;
        }

        let hme = match generated_value
            .pointer("/result/hme")
            .and_then(|v| v.as_str())
            .map(|v| v.to_string())
        {
            Some(email) => email,
            None => {
                consecutive_fails += 1;
                errors.push("Generate succeeded but no email found in response".to_string());
                if consecutive_fails >= MAX_CONSECUTIVE_FAILS {
                    stopped_early = true;
                    break;
                }
                continue;
            }
        };

        let reserve_resp = client
            .request_hme(
                Method::POST,
                &format!("{}/reserve", BASE_URL_V1),
                Some(json!({ "hme": hme.clone(), "label": final_label.clone(), "note": DEFAULT_NOTE })),
            )
            .await;

        match reserve_resp {
            Ok(value) => {
                if let Err(err) = ensure_success(&value) {
                    consecutive_fails += 1;
                    errors.push(format!("Reserve failed: {}", err));
                    if consecutive_fails >= MAX_CONSECUTIVE_FAILS {
                        stopped_early = true;
                        break;
                    }
                    continue;
                }

                generated.push(hme);
                consecutive_fails = 0;
            }
            Err(err) => {
                consecutive_fails += 1;
                errors.push(format!("Reserve failed: {}", err));
                if consecutive_fails >= MAX_CONSECUTIVE_FAILS {
                    stopped_early = true;
                    break;
                }
            }
        }
    }

    let failed = requested.saturating_sub(generated.len() as u32);

    Ok(HmeGenerateResponse {
        requested,
        generated,
        failed,
        stopped_early,
        errors,
    })
}

#[tauri::command]
pub async fn hme_list(
    active: bool,
    search: Option<String>,
    state: State<'_, AppState>,
) -> Result<Vec<HmeEmailItem>, String> {
    let cookie = get_cookie_from_state(&state)?;
    let client = HmeApiClient::new(cookie);

    let response = client
        .request_hme(Method::GET, &format!("{}/list", BASE_URL_V2), None)
        .await?;
    ensure_success(&response)?;

    let keyword = search.unwrap_or_default().trim().to_lowercase();
    let list = response
        .pointer("/result/hmeEmails")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();

    let mut items = list
        .iter()
        .filter_map(map_hme_item)
        .filter(|item| item.is_active == active)
        .filter(|item| {
            if keyword.is_empty() {
                true
            } else {
                item.label.to_lowercase().contains(&keyword)
                    || item.hme.to_lowercase().contains(&keyword)
            }
        })
        .collect::<Vec<_>>();

    items.sort_by(|a, b| b.create_timestamp.cmp(&a.create_timestamp));
    Ok(items)
}

#[tauri::command]
pub async fn hme_list_local(
    active: bool,
    search: Option<String>,
    state: State<'_, AppState>,
) -> Result<Vec<HmeEmailItem>, String> {
    let storage = get_hme_storage(&state)?;
    let mut items = storage.load_all(Some(active))?;

    let keyword = search.unwrap_or_default().trim().to_lowercase();
    if !keyword.is_empty() {
        items.retain(|item| {
            item.label.to_lowercase().contains(&keyword)
                || item.hme.to_lowercase().contains(&keyword)
        });
    }

    Ok(items)
}

#[tauri::command]
pub async fn hme_sync(
    active: bool,
    search: Option<String>,
    state: State<'_, AppState>,
) -> Result<Vec<HmeEmailItem>, String> {
    let cookie = get_cookie_from_state(&state)?;
    let storage = get_hme_storage(&state)?;
    let client = HmeApiClient::new(cookie);

    let response = client
        .request_hme(Method::GET, &format!("{}/list", BASE_URL_V2), None)
        .await?;
    ensure_success(&response)?;

    let list = response
        .pointer("/result/hmeEmails")
        .and_then(|v| v.as_array())
        .cloned()
        .unwrap_or_default();

    let all_items: Vec<HmeEmailItem> = list.iter().filter_map(map_hme_item).collect();
    storage.sync_from_api(&all_items)?;

    let mut items = storage.load_all(Some(active))?;

    let keyword = search.unwrap_or_default().trim().to_lowercase();
    if !keyword.is_empty() {
        items.retain(|item| {
            item.label.to_lowercase().contains(&keyword)
                || item.hme.to_lowercase().contains(&keyword)
        });
    }

    Ok(items)
}

#[tauri::command]
pub async fn hme_deactivate(
    anonymous_ids: Vec<String>,
    state: State<'_, AppState>,
) -> Result<HmeBatchActionResponse, String> {
    run_batch_action(&state, anonymous_ids, BatchActionType::Deactivate).await
}

#[tauri::command]
pub async fn hme_delete(
    anonymous_ids: Vec<String>,
    state: State<'_, AppState>,
) -> Result<HmeBatchActionResponse, String> {
    run_batch_action(&state, anonymous_ids, BatchActionType::Delete).await
}

#[tauri::command]
pub async fn hme_cleanup(
    anonymous_ids: Vec<String>,
    state: State<'_, AppState>,
) -> Result<HmeBatchActionResponse, String> {
    run_batch_action(&state, anonymous_ids, BatchActionType::Cleanup).await
}

enum BatchActionType {
    Deactivate,
    Delete,
    Cleanup,
}

async fn run_batch_action(
    state: &State<'_, AppState>,
    anonymous_ids: Vec<String>,
    action: BatchActionType,
) -> Result<HmeBatchActionResponse, String> {
    let ids = anonymous_ids
        .into_iter()
        .map(|id| id.trim().to_string())
        .filter(|id| !id.is_empty())
        .collect::<Vec<_>>();

    if ids.is_empty() {
        return Err("No email selected".to_string());
    }

    let cookie = get_cookie_from_state(state)?;
    let storage = get_hme_storage(state).ok();
    let client = HmeApiClient::new(cookie);

    let mut success = 0usize;
    let mut errors = Vec::new();
    let mut deactivated_ids = Vec::new();
    let mut deleted_ids = Vec::new();

    for id in &ids {
        match action {
            BatchActionType::Deactivate => {
                let resp = client
                    .request_hme(
                        Method::POST,
                        &format!("{}/deactivate", BASE_URL_V1),
                        Some(json!({ "anonymousId": id })),
                    )
                    .await;

                match resp {
                    Ok(value) => match ensure_success(&value) {
                        Ok(_) => {
                            success += 1;
                            deactivated_ids.push(id.clone());
                        }
                        Err(err) => errors.push(format!("{}: {}", id, err)),
                    },
                    Err(err) => errors.push(format!("{}: {}", id, err)),
                }
            }
            BatchActionType::Delete => {
                let resp = client
                    .request_hme(
                        Method::POST,
                        &format!("{}/delete", BASE_URL_V1),
                        Some(json!({ "anonymousId": id })),
                    )
                    .await;

                match resp {
                    Ok(value) => match ensure_success(&value) {
                        Ok(_) => {
                            success += 1;
                            deleted_ids.push(id.clone());
                        }
                        Err(err) => errors.push(format!("{}: {}", id, err)),
                    },
                    Err(err) => errors.push(format!("{}: {}", id, err)),
                }
            }
            BatchActionType::Cleanup => {
                let deactivate_resp = client
                    .request_hme(
                        Method::POST,
                        &format!("{}/deactivate", BASE_URL_V1),
                        Some(json!({ "anonymousId": id })),
                    )
                    .await;

                let deactivate_result = match deactivate_resp {
                    Ok(value) => ensure_success(&value),
                    Err(err) => Err(err),
                };

                if let Err(err) = deactivate_result {
                    errors.push(format!("{}: deactivate failed: {}", id, err));
                    continue;
                }

                let delete_resp = client
                    .request_hme(
                        Method::POST,
                        &format!("{}/delete", BASE_URL_V1),
                        Some(json!({ "anonymousId": id })),
                    )
                    .await;

                match delete_resp {
                    Ok(value) => match ensure_success(&value) {
                        Ok(_) => {
                            success += 1;
                            deleted_ids.push(id.clone());
                        }
                        Err(err) => errors.push(format!("{}: {}", id, err)),
                    },
                    Err(err) => errors.push(format!("{}: {}", id, err)),
                }
            }
        }
    }

    if let Some(s) = storage {
        let _ = s.set_inactive(&deactivated_ids);
        let _ = s.delete_batch(&deleted_ids);
    }

    let total = ids.len();
    let failed = total.saturating_sub(success);

    Ok(HmeBatchActionResponse {
        total,
        success,
        failed,
        errors,
    })
}
