name: Notify Package Managers

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.TAP_DISPATCH_TOKEN }}
      TAG: ${{ github.event.inputs.tag || github.event.release.tag_name }}
    steps:
      - name: Debug event info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Manual tag input: ${{ github.event.inputs.tag }}"
          echo "Final TAG: $TAG"

      - name: Validate tag
        run: |
          if [ -z "$TAG" ]; then
            echo "❌ Release tag_name is empty" >&2
            exit 1
          fi
          echo "✅ Tag validated: $TAG"

      - name: Dispatch to Homebrew tap
        run: |
          set -euo pipefail
          echo "🍺 Dispatching to Homebrew tap with tag: $TAG"
          RESPONSE=$(curl -sSf -w "\nHTTP_STATUS:%{http_code}" -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/zhaochengcube/homebrew-atm/dispatches \
            -d "$(jq -n --arg tag "$TAG" '{event_type:"atm_release", client_payload:{tag:$tag}}')")
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
          if [ "$HTTP_STATUS" = "204" ]; then
            echo "✅ Homebrew tap notified successfully"
          else
            echo "❌ Failed with status: $HTTP_STATUS"
            exit 1
          fi

      - name: Dispatch to Scoop bucket
        run: |
          set -euo pipefail
          echo "🪣 Dispatching to Scoop bucket with tag: $TAG"
          RESPONSE=$(curl -sSf -w "\nHTTP_STATUS:%{http_code}" -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/zhaochengcube/scoop-atm/dispatches \
            -d "$(jq -n --arg tag "$TAG" '{event_type:"atm_release", client_payload:{tag:$tag}}')")
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
          if [ "$HTTP_STATUS" = "204" ]; then
            echo "✅ Scoop bucket notified successfully"
          else
            echo "❌ Failed with status: $HTTP_STATUS"
            exit 1
          fi
